/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#11131d",
        "surface-dim": "#11131d",
        "surface-bright": "#383844",
        "surface-container-lowest": "#0c0d18",
        "surface-container-low": "#1a1b26",
        "surface-container": "#1e1f2a",
        "surface-container-high": "#282934",
        "surface-container-highest": "#333440",
        "on-surface": "#e2e1f0",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e2e1f0",
        "inverse-on-surface": "#2f303b",
        "outline": "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        "primary": "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        "secondary": "#d0bcff",
        "on-secondary": "#3c0091",
        "secondary-container": "#571bc1",
        "on-secondary-container": "#c4abff",
        "tertiary": "#2fd9f4",
        "on-tertiary": "#00363e",
        "tertiary-container": "#008395",
        "on-tertiary-container": "#000608",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-fixed": "#a2eeff",
        "tertiary-fixed-dim": "#2fd9f4",
        "on-tertiary-fixed": "#001f25",
        "on-tertiary-fixed-variant": "#004e5a",
        "background": "#11131d",
        "on-background": "#e2e1f0"
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
